### ISSUE TITLE
No such file or directory: './datasets/train.en.segmented.vocab'

### ISSUE THREAD

**Issue by minty99** [strutive07/transformer-tensorflow2.0#11]
pretrained model로 인퍼런스를 돌려보기 위해 dataset과 checkpoint 파일들을 다운로드하고 `python test.py` 를 실행했는데, 저 파일이 없다는 오류가 발생합니다. 어떻게 고칠 수 있을까요? 다른 파일들을 확인해보아도 특별히 저 파일을 생성하는 코드는 찾지 못했습니다.

**Comment by strutive07** [comment]
BPE pretrained model의 정보를 README에 넣어드리지 않아서 생긴 문제인듯합니다.
BPE를 학습시키는 코드는 Dataloader.load에 존재하는데, test코드에서는 이 함수를 실행하지않아 생긴 오류 인듯합니다.

KST 기준 2020.02.07 ~ 2020.02.08 이내로 README에 pre trained BPE model을 공유 및 저장위치를 공유해드리고, 위 버그는 PR을 만들어 solve하겠습니다.

피드백 정말 감사합니다!

**Comment by strutive07** [comment]
PR https://github.com/strutive07/transformer-tensorflow2.0/commit/fef066d72273c1837dda5401fcf2278799bc1d86 에서 해당 download link를 추가 해 두었습니다.
dataset directory에 WMT14 데이터와 같은 depth로 추가해주시면 됩니다. 
예시)
./dataset
```
> pwd
/home/ubuntu/dataset
> ls -l
.
..
train.en
train.en.segmented.vocab
train.en.segmented.model
```

**Comment by strutive07** [comment]
이 issue는 close 하겠습니다. 추후에 지속적으로 문제가 다시 발생한다면, 새로 issue를 열어주시면 감사하겠습니다.
